const packageData = 'ybruvapdgixszyckwtfqjonsie mbruvapxghslyyckwtfqjonsie mbruvapdghslzyckwtkujonsie rwruvapdghxlzyckwtfqjcnsie obruvapdgtxlzyckwtfqionsie lbruvapdghxqzyckwtfqjfnsie mbrunapdghxlzyccatfqjonsie mbruvapdghxlzyokltfqjdnsie ybruvapdghxlzmckwtfqjmnsie mbruwaadghxdzyckwtfqjonsie muruvapdghxlzyckvtfqjonsim mbruvapdghxlkyckwtxqjonjie mbruvaqdghxlzyckwtfqjrnnie mwruvapdghdlzyckttfqjonsie mbruvapdgtelzyckwxfqjonsie mbruvapdohxlzvckwtfqjonhie mbrugapdgbxlzyckwtfqjynsie mbruvapdghxlzyckwtlqjonjiu mbruvapwghxlzyckwafqjonbie wbruvapdghxlhyckwtfqjonsii mbruvapdghxlzyckwtcqnonsiq mbyuvapighxlzybkwtfqjonsie mbrrvapdghxvzyckwtfqjonsio mhruvapdghrlzyckwtfzjonsie mtruvapvghxlzyckwtfnjonsie mmrlhapdghxlzyckwtfqjonsie mbruvapdgpxlzyjkwtfqjovsie mbrucapdghxlzymkwtzqjonsie mbeuvafdghxlzyckwtfqjonwie mbruvapcghxlayckwtfqjonsii mbruvabdghxlzyckwtfqyansie mbruvjpdghxlzyckwtfqgfnsie lbruvapdghxlzyckwtfqjonriv mbrupapdghxlzycjwtfqronsie mbpuvapdthxlzymkwtfqjonsie mbiuvapdgixlzyckwxfqjonsie mbruvapdghxyzyckwtfcjonsbe mbrurapkghxlzyckwtfqjonzie mbrufapdrhxlzyciwtfqjonsie mbruvapdghxlzbckwtfqjoisae ubruhapdghxlzuckwtfqjonsie mbruvapdjhulzyckwtfqjonshe mbruwapdgyxlzyckntfqjonsie mwruvapdghplzyckwtfqjonsme mbruvapjghtlzyckwtfqgonsie pbruvapdghhlzyckwtfrjonsie mbruvgpdihxqzyckwtfqjonsie mbruvahdohxlzyckwtfijonsie ibuuvapdghxlzyckwtfqjofsie mbruvandghxlzyckwtfqjrnxie mbrjvlpdghxlzyckwgfqjonsie mbruvapogfxlzyckotfqjonsie mbruvrpdghxlzyckutfejonsie mbruvbpdghxlzyhkwtfqjonsip mbruvapdghxlzyckmnfqjensie mbruvapdghvlzyckwtfqjowsix mbruvakdgholzwckwtfqjonsie mbruvapdghxlzackwtfqconsae mbruvapdghxlzyqvwtfqjlnsie mprrvapdgfxlzyckwtfqjonsie mbrunacdghxlhyckwtfqjonsie obruvapdgsxlzyckwtfqjonvie murcvapdghslzyckwtfqjonsie mbruvapdghxlzyzkwmftjonsie mbrwvapdgtvlzyckwtfqjonsie mbxuvapdghxlzqcnwtfqjonsie mbruvaddghxboyckwtfqjonsie mhruvwndghxlzyckwtfqjonsie mbrdvapdghxlzyckwmpqjonsie mbruvapdgyxlzyckizfqjonsie mbruvapdghxlzlckwtfqeowsie mbruvbpdgrxlzyckwtfqjonsxe mbruqapoghxlzyckwtvqjonsie mbouhapdghmlzyckwtfqjonsie mbruvapjghxidyckwtfqjonsie mbsuvapkghxlkyckwtfqjonsie mbruvlpdghxlzycrwtfqjonsis mcrueapdghxlzyckwtfqjynsie muruvapngbxlzyckwtfqjonsie mbruvapdghxlzycawtfyjojsie mbruvbpdghxczyjkwtfqjonsie ybduvapdghxnzyckwtfqjonsie mbruvbpdghxlzyckwtfbjousie mbouvapdghxlzycbwtfqponsie mbruvaedghplzycgwtfqjonsie mbrhvapdghxlzyckytfqjgnsie mbruvapdqbxleyckwtfqjonsie mbruvapddhhldyckwtfqjonsie mbruvapdghxlwrckwtfqjondie mbruvapdmhxlzyckwtfqkonsve xbbuvapdghxlzyckwtfkjonsie mbruvapdghxlzyckwcfqjunkie mbruvapdghxlzyckwtfqxonfib mbrtvapkghxlzyckwtfqeonsie mbruvazdghxldymkwtfqjonsie kbruvapddhxlzfckwtfqjonsie mbouvapdghxlpyckwtfqjoosie mbauvapdghxlzyckwtfqjszsie mbruvapdghtlzyckntfqtonsie mbruvipdggxlzbckwtfqjonsie mbruqapdghrlzyckwtfqjznsie myruvacdghxlzyckwifqjonsie mbruvapdghxlzuckwtfkjocsie mwjuvapdghxlzyckwtfqjonsxe mbruvapxghxlzickwtfqjobsie mbrupapdghxtlyckwtfqjonsie meruvapdjjxlzyckwtfqjonsie mbruvkodghxlzyckwofqjonsie mbruvapdgexlzyckwtgkjonsie mbruvapwghxlzyckwtcqjonsiw mbruvapdghxlzykkwtfqtoxsie mbruvapdahxlzycgwtfwjonsie mbruvapdgwxlhyckhtfqjonsie mbruvapbghxlzycbhmfqjonsie mbruvapdghxvzyzkwtfqjonsin mbrcvapdqhxlzyckwyfqjonsie zbruvaxdghxlzyckwgfqjonsie mtruvapdghxlilckwtfqjonsie bbruvapdghxlzyckwtfmjonsxe mbruvajdghxlzyckwtfqfwnsie mbruvapdgkxlzyckwtfqionpie rbruvapdghxlryckwdfqjonsie mbruvandghxlzyckwmfvjonsie mbruvahdghxlzeckwtfqjonsme mbruvnpcghxlzyckwtfqjobsie mbruvapdghqlzyckwtfbjonsiy mbruvavdghxlzyckwufqjodsie mbruvapdghxlzyckwtfzmovsie mbruvlpdghxuzyckwtfqjoesie mbruvopdghxlzycwwtfqjansie obruvapdghglzybkwtfqjonsie mbpuvlpdghxlcyckwtfqjonsie mbruvaidghxlzyckwtfmjonoie mbruvapdihxzzyckwtfqjonsiy mbquvapdghxlzyckwtfqconsme mbruvapdghslzyckqtfqjojsie mbrzdapdghxmzyckwtfqjonsie mwruvapdghxozyckwtfqjonsxe muruvapdgfxlzyckwtfqjojsie wtruvapdghxlzyckvtfqjonsie mbruvapdghxlzyckysfqjxnsie mbruvrpdghxczyckktfqjonsie mbquvapdghxlryckwtfqjonsne mbruvapdghflzycvwtfqjpnsie mbruvapughclzyckwtfqjonsin mbrhvapdghxlpyckwtfqjonsre mbruvapdgtxlzyckwtfqjoosit mbrupapnghxhzyckwtfqjonsie mmvuvapdvhxlzyckwtfqjonsie mbruvaptghxlzyckwtfqjotsse mgruvapvghxlzyckwtfqjonsix mbrupapdghxszyckwtfqjunsie mbruvkpdghelzyckwtfqjpnsie mbruvrrdghjlzyckwtfqjonsie mbruvapdghnlzyckwtfkjonsze mbruvwpdghxlzyckwtfqhoysie mbrsvapdfhxlzyckwtfqjobsie mbruvapdgexezymkwtfqjonsie ybruvapdghxlzyckwtfqxonsiw mrruvapdghxdzyckwtfqjossie mbruvapdghtlzyckwtfqconsiu mbrpvapdghxlzlckwpfqjonsie mbruvjpdghslzyckwtfqjjnsie mhruvapoghxlzyckwtfvjonsie mbrubqpdghvlzyckwtfqjonsie mbruvapdghxlzackwtfqconsiw mbruvapdgnxlzkckwtfqjdnsie mbrudapgghelzyckwtfqjonsie mbruvapdghxlzlakwbfqjonsie mbpuvapdghxlzyckwtuqjonjie abruvapdghxlzykkwtfqjonzie mbrupupdghxlsyckwtfqjonsie mbrsvupdghxlzyckwtfqjonkie mxruvgpdghxllyckwtfqjonsie mbrnvapdghxlzycbwtfqfonsie mbrbxapdghxlzyckttfqjonsie mbnuvapdghxlzyxkwtmqjonsie mbrfvapdghjlzickwtfqjonsie mbhuvupdghxlzyxkwtfqjonsie mbrcvapdghxluyckwtfqjznsie mbruvapdghxlzyckwofqjoxsiz mbrevapdghxloyckwtfqjonnie mbruvipdghnlzyckwtfqjopsie mbxxvaptghxlzyckwtfqjonsie mbruvcpdghxlztckwtjqjonsie mqruvlpdghxlzyckotfqjonsie mbruvapdgqxlzyckwtfqjpvsie mbruvapdgvxlzyjkwtfqjbnsie mbruvapdghxlgyckwtfqcocsie mbruvapdghxkwyckwtfqjoqsie mbrgvavdghxlzyckwxfqjonsie qbruqapdgvxlzyckwtfqjonsie mbauvapdghxlzgckwtfqjunsie mbruvapdgdxluyckwtfqjoosie mbruvapdghxlzykkwtfqwobsie mbruvapdghxlzhcnwtfqjonqie mbruvapdghxlzycbhmfqjonsie mbruvapdghxluyczwtfqjontie mbruvapnghxlzyckwnfqjonbie moruvapdghxlzcckwtfqponsie mbruvapfgxxlzyckwtfqjunsie mbruvapdghxlryckvtfejonsie mbrzvapdghxlzvcbwtfqjonsie mbruvapdgqxlzyckwcfqjonsce abruvupdrhxlzyckwtfqjonsie mbrubaptghxlzyckwtfqjondie mgruvapdgpxlzyckwtfijonsie mbruvapdghxczlckwtfujonsie mbruvapdgmmlzyckwtfqjonsir mbruvapdhhxltyckwtfdjonsie mbruvapdghxlzyckwtfdjjnste mbrdvzpdghxlcyckwtfqjonsie mbruvapdghxlzyckwtnqbonsim mbrovapdghxlzyckwtfpjousie mymuvapdghxlzyjkwtfqjonsie mbpuvapdghxlzyckwtfljcnsie mbrxvapdghxlzyclwtfqjonpie mbrueapdghxlzyckwtfqjopsia mbruvapdghxlzycdwtfqjbfsie tbruvavdghxlzyckwtmqjonsie mbduvapdghxlzyckwrfqjrnsie mkrsvapughxlzyckwtfqjonsie mbruvapdghylzyckwtfqtolsie mgruvapdglxldyckwtfqjonsie mbrunapdghclzyckwtfqjonsiy mbruvapdgrxlxyckwtfgjonsie mbruvapdghxpzbckftfqjonsie mbruvcpdghxyzyckotfqjonsie mbruvapdghxlsyckwtfqcqnsie mbruvapdghxlzzckwtfqjonskf mbruvppdghxlzfckwtfqjgnsie mbhuvapdghxlzytkwtfqjonoie mbruvapdghxlzvrkwtfqjjnsie mbmuvapdghxuzyckwtfqjonsze mbruvapdghnlzycnwtfqjonsil mbruvapdgholzyckitfqjonsia mbruxapdghxlmyckwtfqbonsie mbauvapdgholzyckwtfqjolsie mbruvapdghxlzyckwtfqjotslq dbrutapdghxlzyckwtfqjonsiv mbruvapdzhxlyyckwtfbjonsie mmruaapsghxlzyckwtfqjonsie mbruvaldgqxqzyckwtfqjonsie mbruvaodghxdzyjkwtfqjonsie mbrcmatdghxlzyckwtfqjonsie mbrqvapdgtxlzycewtfqjonsie mjruvapdghzlzyckwtfqjonrie mbruvapdghxopcckwtfqjonsie mbruvapdghxszycwwtfqjoqsie mbruvapdgoxezyckwtjqjonsie';
const sampleData1 = 'abcdef bababc abbcde abcccd aabcdd abcdee ababab';
const sampleData2 = 'abcde fghij klmno pqrst fguij axcye wvxyz';

function packageCheckSum(data) {
  const dataArray = data.split(' ');
  let countExactlyTwo = 0;
  let countExactlyThree = 0;

  for (let curDataIndex = 0; curDataIndex < dataArray.length; ++curDataIndex){
    let curDataElement = dataArray[curDataIndex];
    let tempPackageCharObject = {};
    let tempTwiceFlag = false;
    let tempThriceFlag = false;

    for (let curCharIndex = 0; curCharIndex < dataArray[curDataIndex].length; ++curCharIndex){
      let curChar = curDataElement[curCharIndex];
      if (!tempPackageCharObject.hasOwnProperty(curChar)){
        tempPackageCharObject[curChar] = 1;
      } else {
        tempPackageCharObject[curChar] += 1;
      }
    }

    for (let count in tempPackageCharObject){
      if (tempPackageCharObject[count] === 2){
        tempTwiceFlag = true;
      } else if (tempPackageCharObject[count] === 3){
        tempThriceFlag = true;
      }
    }

    if (tempTwiceFlag){
      countExactlyTwo += 1;
    }
    if (tempThriceFlag){
      countExactlyThree += 1;
    }

  }
  // console.log(countExactlyTwo);
  // console.log(countExactlyThree);
  // console.log(countExactlyThree * countExactlyTwo);

  return true;
}

packageCheckSum(sampleData1);
packageCheckSum(packageData);

function correctPackageId(data){
  const dataArray = data.split(' ');


}

correctPackageId(sampleData2);
